from sqlalchemy import create_engine
import os
from dotenv import load_dotenv

# 1. Load file environment configuration
load_dotenv()

def get_db_url():
    """Build string database connection from environment variables"""
    user = os.getenv("DB_USER")
    password = os.getenv("DB_PASSWORD")
    host = os.getenv("DB_HOST")
    port = os.getenv("DB_PORT")
    dbname = os.getenv("DB_NAME")
    
    # Check wether variabel succesfully loaded (for debugging)
    required = [user, password, host, port, dbname]
    if not all(required):
        raise ValueError("One or more DB environment variables are missing.")


    return f"postgresql://{user}:{password}@{host}:{port}/{dbname}"

def get_engine():
    # 2. Call the URL builder function
    db_url = get_db_url()
    return create_engine(db_url, echo=False)
    # The echo flag is for debugging purposes, it logs all the SQL statements generated by SQLAlchemy
    # In production, you might want to set echo to False to reduce log verbosity.
